### ISSUE TITLE
1.12.1 Survival server console spam could not pass event BlockBreakEvent

### ISSUE THREAD

**Issue by dado243** [EthanTG/AntiAura#100]
Latest anti aura, 1.12.1, happens when player breaks block or something i dont know screenshot:  http://prntscr.com/gb835m

**Comment by EthanTG** [comment]
@joehot200 come back!

**Comment by Ironic8b498** [comment]
getting same error, when breaking stone, gold ore, coal ore, iron ore, andesite, dorite, ext

**Comment by joehot200** [comment]
Fixed for 10.05
