### ISSUE TITLE
Double-Jump - 'Step' Bug - 11.06

### ISSUE THREAD

**Issue by Fruitiful** [EthanTG/AntiAura#104]
**Minecraft Version:** 1.12.1
**AntiAura Version:** 11.06
**Hacked Client:** N/A
**Description:** Whenever I try to utilise [this](https://www.spigotmc.org/resources/doublejump.42518/) double-jump plugin on a private server, Anti-Aura drags me back for 'Step'.

**Comment by joehot200** [comment]
Hi @Fruitiful,

Unfortunately this isn't something that can be easily solved, so I recommend just disabling SingleBlockPackets. Step for multiple blocks will still be blocked anyway.

**Comment by joehot200** [comment]
Tell you what, I'll reopen this issue and see if I can create a fix.

**Comment by joehot200** [comment]
Fixed for 11.07.

**Comment by EthanTG** [comment]
:o
