### ISSUE TITLE
Glide bypass!

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#105]
**Screenshot (or video recording):** 
https://gyazo.com/59e181e39b47f70b9d96955dd8c8dee2
https://gyazo.com/5ceae4d1076b1bab61fb0ac18d0dc8fa

**AntiAura version:** 11.06

**Minecraft version:** 1.8.8

**Hacked Client (Set to N/A if none):** Wurst 6.0 1.8

**Description:** ...... no detections at all. Not sure if this is bug or bypass.

**Comment by joehot200** [comment]
Was fixed last update.
