### ISSUE TITLE
Step bug while flying

### ISSUE THREAD

**Issue by Personinblack** [EthanTG/AntiAura#107]
**Screenshot (or video recording):**  Don't think necessary

**AntiAura version:**  11.07

**Minecraft version:**  1.8.8 PaperSpigot

**Hacked Client (Set to N/A if none):**  Zues 0.9

**Description:**  If you double press spacebar when you are high above the ground and flying straight, you can get detected as stepping.

**Comment by EthanTG** [comment]
Just because you don't think it's necessary doesn't mean you shouldn't put in a video. We don't exactly know what you mean. A lot of the information comes from a video/screenshot so if you could add one in that'd be helpful. If it's rare it's ok if you don't get one (usually).

**Comment by joehot200** [comment]
Can we have more information about the issue?

**Comment by Personinblack** [comment]
I guess I wasn't able to explain it. Here is a video of it: https://youtu.be/El8priNDJgg

All I'm doing is holding ctrl + w while flying and when I gain enough speed I double press space to toggle fly.

**Comment by joehot200** [comment]
Thank you. Fixed for 11.08.
