### ISSUE TITLE
Occlusion false positive 

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#109]
**Screenshot (or video recording):** 
https://gyazo.com/2eb6064440b167a580c9ccba1c150541
https://youtu.be/o0dTwBuoLFQ

**AntiAura version:** 11.07 (OTS)

**Minecraft version:** 1.8.8 

**Hacked Client (Set to N/A if none):** Wurst 6.11.1 OF (1.8.8)

**Description:** I was literally hitting in the air not through a block and I got kicked for Occlusion. I was using 90 FOV and 70 FOV Killaura and I was still kicked! Occlusion needs to be reworked.

**Comment by joehot200** [comment]
"I was using killaura"

Umm.....

**Comment by EthanTG** [comment]
70 FoV killaura = basically just a fraction above legit pvp that shouldn't be detected?

**Comment by Personinblack** [comment]
You are in between lots of entities which means you are probably hitting through entities. If you manage to get detected without Killaura that could count as a false positive. Also FoV is not changing the fact that Wurst's Killaura can hit through entities.

**Comment by joehot200** [comment]
Thanks @Personinblack. When I made my first reply I hadn't seen the video (as I was on a mobile connection). I can close the issue now. :)

**Comment by EthanTG** [comment]
@Personinblack 💯
