### ISSUE TITLE
FastClimb/FastStairs bypass/not detected

### ISSUE THREAD

**Issue by ItsMennyo** [EthanTG/AntiAura#11]
###
#Server Version: git-Spigot-7228328-50b75cd (MC: 1.12)
#Client Version: LiquidBounce b26.2 | 1.8.9
#Server Info: localhost (ping: 0)
#AntiAura Info: Default config and latest version
###
#BYPASS/NOT DETECTED 1:
#
#FastClimb (bypass mode: normal)
#https://gyazo.com/1d65b7c5145208bb5c90dae787acbaaa
###
#BYPASS/NOT DETECTED 2:
#
#FastStairs (mode: NCP and AAC) and Step (mode: NCP and height: 1.0)
#https://gyazo.com/c16f600f7d0e4d6095779dca73372703
###

**Comment by EthanTG** [comment]
FastStairs = Step BTW

**Comment by ItsMennyo** [comment]
The hack on that hack client is called FastStairs...

**Comment by joehot200** [comment]
Stepping up 1 block is not blocked intentionally, unless you enable SingleBlock. Therefore is not a bypass. Also if you really want to block that kind of thing you can configure Step to not allow multiple blocks in a certain amount of time, removing the advantage.

Will be looking into solving the FastClimb bypass.

**Comment by ItsMennyo** [comment]
Moved to [HERE](https://github.com/EthanTG/AntiAura/issues/29).
