### ISSUE TITLE
Critical bugs while detecting 'NoFall' & 'Spider'

### ISSUE THREAD

**Issue by CatNote** [EthanTG/AntiAura#111]
REQUIRED FORMAT:

**Screenshot (or video recording):** 
https://vimeo.com/231972819 - NoFall
https://vimeo.com/231972872 - Spider

**AntiAura version:**
11.07

**Minecraft version:**
1.12.1

**Hacked Client (Set to N/A if none):**
N/A

**Description:**
Everything on recording
I didn't using any hack programs on this video

**Comment by joehot200** [comment]
Fixed for 11.08.
