### ISSUE TITLE
Detect hitting entities above a block

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#117]
**Name of feature:** look at title

**Description:** Some killaura can still hit players when they are above a block. Right now occlusion only blocks hitting through blocks x-z but not Y so try that @joehot200

**Comment by joehot200** [comment]
Pretty sure occlusion blocks Y axis too

**Comment by EthanTG** [comment]
nope

**Comment by joehot200** [comment]
The problem is just that occlusion didn't block it if the distance was too close. Changed for 11.08.
