### ISSUE TITLE
Killaura long detection?

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#119]
**Screenshot (or video recording):** https://youtu.be/3KqPW8jkYJA

**AntiAura version:** 11.07

**Minecraft version:** 1.8.8

**Hacked Client (Set to N/A if none):** Flux B11
 
**Description:** It took a *very very long time* to detect Killaura. Is this a config related thing or a problem with AntiAura?

**Comment by Personinblack** [comment]
This must be your config. Mine detect switch aura in seconds...

**Comment by EthanTG** [comment]
This is an unmodified config @Personinblack

**Comment by joehot200** [comment]
I'm going to declare this closed because 1, we can't dupe it, and 2, the new Position check would hopefully block this now.

Feel free to make a new issue with an easily duplicatable problem.
