### ISSUE TITLE
ESP issue still.... 

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#124]
**Screenshot (or video recording):** https://gyazo.com/f55efec1c26989fbc23372c9f8984345

**AntiAura version:** 11.08

**Minecraft version:** 1.8.8

**Hacked Client (Set to none if none):** None

**Check Config (e.g. if this was a Step bug then you would put step config):** N/A

**Description:**
...

Referenced to #95

**Comment by joehot200** [comment]
Not a big.

**Comment by EthanTG** [comment]
big?

**Comment by joehot200** [comment]
Bug*

**Comment by EthanTG** [comment]
fix it bruh... idc if it's a bug or not
