### ISSUE TITLE
[FP] Elytra

### ISSUE THREAD

**Issue by johand199** [EthanTG/AntiAura#15]
[16:39:05 INFO]: Johand dragged back: Speed
[16:39:07 INFO]: Johand kicked for teleportation due to flying too far with Elytra.
https://youtu.be/9xQsQ0JQmQc

**Comment by joehot200** [comment]
Confirming as bug, aiming to solve next update.

**Comment by joehot200** [comment]
Will be fixed for next update.

**Comment by EthanTG** [comment]
@joehot200 you should close issues WHEN The next update comes out, just for reference

**Comment by joehot200** [comment]
@EthanTG I will be closing issues when I have fixed them in AntiAura's code, such as when I have done here. I understand the confusion, but if I didn't do this, then I would be looking at bugs multiple times. 

Sorry for the confusion, but it is easier for me to work this way.

**Comment by joehot200** [comment]
Also just to clarify this is when it is FIXED in the code, not just an "I'm aware of this and planning to fix it" type thing.

**Comment by EthanTG** [comment]
@joehot200 but wouldn't you be looking at them multiple times without the label?
