### ISSUE TITLE
ESP Issue (10.95)

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#2]
**Screenshot:** Unavailable

**AntiAura version:** 10.95

**Description:** Player disappeared for 2 seconds after I watched him

**Comment by joehot200** [comment]
This was fixed in one of the previous updates, however I neglected to mention it in the update log. Oops!

**Comment by EthanTG** [comment]
It's still happening for me though @joehot200

**Comment by EthanTG** [comment]
Issue has been reopened at #52
