### ISSUE TITLE
Count versions starting at 11.0

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#23]
**Name of feature:** Count versions starting from version 11.0
 
**Description:** Count versions starting from version 11.0. This can help people know what version they are exactly downloading. Every update should have it's own update.

11.0, 11.01, 11.02, etc.

Sometimes there might be an update that's related to the previous update. In that case...

11.02-b1 :)

**Comment by ItsMennyo** [comment]
True...

**Comment by EthanTG** [comment]
yep

**Comment by joehot200** [comment]
I only ever didn't do this once, this is what was being done already

**Comment by EthanTG** [comment]
@joehot200 can you please explain what you mean? You didn't do this for 10.98 as the Spigot page still displays as 10.97. I also mean like when updating something maybe you can put the version number in [].

For *example* this could be the 11.0 title:

[11.0] The big update! Tons of bugfixes, new additions, bypass patches, and more!

**Comment by joehot200** [comment]
The plugin.yml should say 10.98. If if says 10.97, that was a typo and not an intentional decision.

**Comment by EthanTG** [comment]
Plugin.yml?
