### ISSUE TITLE
Bug with AntiXRay and TPS drops.

### ISSUE THREAD

**Issue by ItsMennyo** [EthanTG/AntiAura#24]
**Info**:
- Type: Bug
- Client: 1.8.9-Optifine_HD_U_H8
- Server: Official AntiAura Test server

**Description**:
- Bug with AntiXRay and TPS drops.

**Settings**:
- None.

**Video/Proof**:
- https://gyazo.com/fc84ffb65ac63a297ae31d93953ceb96
- https://gyazo.com/1dfee79f371f186fc2253fb1a5a91128

**Comment by joehot200** [comment]
Has been fixed in the code for the next update, with the introduction of the MaxChunksPerIntervalMult option in the config (which defaults to 2).
