### ISSUE TITLE
[Bypass] Full on speed + XRay

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#25]
**Screenshot (or video recording):** https://youtu.be/DOyEAN67d1Q :(    

**AntiAura version:** 10.98

**Hacked Client (Set to N/A is none):** Flux B11 (I think this works on some other clients too)

**Description:** There is an existing semi-bypass for Full-On speed and a FULL bypass for XRay.
PLEASE FIX AT 11.0

**Comment by joehot200** [comment]
Speed isn't bypassing anything as it's not actually travelling faster than a normal client, hence why it isn't being dragged back. That's a suggestion.

I'm not sure why x-ray seems to be doing that, I can investigate it.

**Comment by joehot200** [comment]
The X-Ray bypass was patched in the last update, and the Speed thing wasn't a bypass, so this can be closed.
