### ISSUE TITLE
Bypass for FastClimb on LiquidBounce.

### ISSUE THREAD

**Issue by ItsMennyo** [EthanTG/AntiAura#29]
**Info**:
- Type: Bypass
- Client: LiquidBounce b26.2 | 1.8.9
- Server: Official AntiAura Test server

**Description**:
- Bypass for FastClimb on LiquidBounce.

**Settings**:
- FastClimb:
  - Bypass:
      - Normal

**Video/Proof**:
- https://gyazo.com/eef31f62dc0e688cd2ab2c0aa87a01a7

**Comment by joehot200** [comment]
Will be fixed in the next version release.
