### ISSUE TITLE
Bypass for LiquidWalk on LiquidBounce.

### ISSUE THREAD

**Issue by ItsMennyo** [EthanTG/AntiAura#31]
**Info**:
- Type: Bypass
- Client: LiquidBounce b26.2 | 1.8.9
- Server: Official AntiAura Test server

**Description**:
- Bypass for LiquidWalk on LiquidBounce.

**Settings**:
- LiquidWalk:
  - Type:
    - NCP

**Video/Proof**:
- https://gyazo.com/8af80614ca4bc1328945dffc99dd5660

**Comment by joehot200** [comment]
I would be interested on what would occur if you were on a larger body of water.

**Comment by ItsMennyo** [comment]
@joehot200 What do you need to know?

**Comment by joehot200** [comment]
@itsMennyo show me what happens on a large body of water.

**Comment by ItsMennyo** [comment]
@joehot200 This: https://gyazo.com/ec98f05bec0a2630706b4a878920d2a9

**Comment by joehot200** [comment]
I have attempted to solve this in the next update. Please reopen if issue is not solved after the next update is released.
