### ISSUE TITLE
Step Critical bug

### ISSUE THREAD

**Issue by onemoreplays** [EthanTG/AntiAura#32]
Video: https://www.youtube.com/watch?v=gdziWWZD10s

AntiAura version: 10.98 (On official test server)

Hacked Client (Set to N/A is none): Nivia b2

Description: As you saw at video, I wasn't able to walk longer distances or use any TP or Warp commands.. Please fix.

**This is a problem with SingleBlock step!**

**Comment by ItsMennyo** [comment]
Problem was that @EthanTG has configured the step check so that one block high step was also blocked but that caused problems and with the default config there are no problems like this anymore...

**Comment by EthanTG** [comment]
@ItsMennyo This also means that SingleBlock has a problem so let's reopen this?

**Comment by EthanTG** [comment]
Reopened without 11.0 milestone as this option is false by default.

**Comment by ItsMennyo** [comment]
Joe said earlier, _Stepping up 1 block is not blocked intentionally, unless you enable SingleBlock. Therefore is not a bypass. Also if you really want to block that kind of thing you can configure Step to not allow multiple blocks in a certain amount of time, removing the advantage._

Sooo...

**Comment by joehot200** [comment]
Closed. Configuration changes may be made in future to help reduce the type of bypass seen in the video. However, the behavior is NOT unintended, and is therefore not a bug.
