### ISSUE TITLE
[CRITICAL] NoSlowdown not functioning!

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#38]
**Screenshot (or video recording):** https://youtu.be/Guak85J0axw
(Video also has a FULL semi-speed bypass!!!)

**AntiAura version:** 10.98

**Hacked Client (Set to N/A is none):** Flux B11, Zeroday B6, other clients by other testers

**Description:** May have been something wrong when you coded it @joehot200?

**Comment by joehot200** [comment]
I'm going to close this until it's clarified. For example food speed is blocked, but NoWeb is not. I can't consider something a legitimate bug until it's clarified as to what the problem is, sorry.

**Comment by joehot200** [comment]
Many forms of NoSlowdown are blocked, for example food, bows, slowness potions, water, etc. NoWeb isn't blocked, is that what you meant?

The issue needs clarification.

**Comment by EthanTG** [comment]
Swords aren't blocked
Bows aren't blocked
Eating food while walking isn't bloked

**Comment by joehot200** [comment]
@EthanTG all of those things are blocked. I will need more proof.

**Comment by EthanTG** [comment]
@joehot200 I have uploaded the video but have not shown Bow proof. You can test it yourself, but I'm sure it's not blocked. Maybe you did something wrong when coding 10.98 and deleted something?

**Comment by joehot200** [comment]
I duplicated this issue and have developed a fix which will be released in next update.

I will also stress that it was *only* blocking that wasn't working. Eating food, as well as shooting bows, was still blocked. However I decided that could be tightened a bit too, and I added config options to them.
