### ISSUE TITLE
Unusual LEGIT Criticals Threshold peaking

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#39]
**Screenshot (or video recording):** ![2017-07-25_13 43 41](https://user-images.githubusercontent.com/29691919/28585786-6fb4575e-713f-11e7-9ab9-68a3a5b0fa64.png)
![2017-07-25_16 54 08](https://user-images.githubusercontent.com/29691919/28593370-1024caa6-715a-11e7-8049-35bbb4414706.png)

**AntiAura version:** 10.98

**Hacked Client (Set to N/A is none):** Zeroday B11

**Description:** Fighting mobs in water with regen 255 on forever with Legit criticals caused the CriticalsThr to hit 6.6 which was unusually high for PvP.

Also, using Jesus + LEGIT Criticals in the water caused a kick at Threshold 7.5 which was unusual. (I lowered 8 to 7 for crits threshold). This probably would've happened too if it went up to 8 on normal configs. 

*Should you be unable to provide information for a certain requirement, your bug may be closed unless you add further information or get low priority.*

**Comment by joehot200** [comment]
Does this ONLY occur in water?

I am check it out.

**Comment by EthanTG** [comment]
This also kind of occured on land too (I got the occasional kicks) with CriticalsThreshold at 7.0 and SafeHitDecrease at 2.0. @joehot200

**Comment by joehot200** [comment]
I've done some changes to hopefully make this happen less, but please reopen if issue keeps occurring.
