### ISSUE TITLE
Try to break grass while it is protected kicked me for FastBreak.

### ISSUE THREAD

**Issue by ItsMennyo** [EthanTG/AntiAura#41]
**Info**:
- Type: False Positive
- Client: 1.8.9-Optifine_HD_U_H8
- Server: ItsMennyo Network 2.0
- AntiAura version: 10.98
- Config: Default
- Check: FastBreak

**Description**:
- Try to break grass while it is protected kicked me for FastBreak.
- Sorry that it has a "priority" label because on my main server players are also kicked for this.

**Video/Proof**:
- https://gyazo.com/ead597af03d3422b13359c0e65618fe7

**Comment by EthanTG** [comment]
Please clarify. I don't know what you mean by "try to break glass while it is protected."

**Comment by ItsMennyo** [comment]
I have my spawn protected so none can break things. If people try to break grass they get kicked for FastBreak.

**Comment by joehot200** [comment]
It shouldn't check if the break is cancelled. Make sure your plugin is not cancelling it on a high priority. I can raise the priority when I get home from holiday.

**Comment by joehot200** [comment]
Also please clarify if they are being kicked for the MaxSurvivalBlocksPerSeocond or the GhostHand part of the check.

**Comment by ItsMennyo** [comment]
When I try to break 1 block of grass, nothing happens but when I walk and that I hit 2 different blocks of grass, I'll be kicked.

I use Essentials AntiBuild so no idea what priority it uses or has.

When I set "MaxSurvivalBlocksPerSecond" at 999, I'm still get kicked...

**Comment by EthanTG** [comment]
@joehot200 please go on discord. Support is required!

**Comment by joehot200** [comment]
@EthanTG I don't have discord on my phone

**Comment by ItsMennyo** [comment]
@joehot200 Instal it XD

**Comment by EthanTG** [comment]
exactly :D

**Comment by joehot200** [comment]
This has been patched for the next update.
