### ISSUE TITLE
Rare unknown dragback bug

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#43]
**Screenshot (or video recording):** https://gyazo.com/6cc0963ace051d74f0f864b010fedaa5

**AntiAura version:** 10.99

**Hacked Client (Set to N/A is none):** Flux B11

**Description:** I was in /warp killauratest standing on the cobblestone wall right next to the zombies when 5 seconds later I got dragged down INTO the zombies and I had no hacks on!

**Comment by joehot200** [comment]
Will close, as we cannot duplicate this. We may reopen when there is more evidence or information about this.

**Comment by EthanTG** [comment]
Evidence has been added. @joehot200

**Comment by EthanTG** [comment]
@joehot200 Issue has been resolved in 11.01
