### ISSUE TITLE
[FP] PvP speed dragback

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#44]
**Screenshot (or video recording):** N/A (happened out of the blue)

**AntiAura version:** 10.98 (OTS)

**Hacked Client (Set to N/A is none):** Flux B11

**Description:** I was hitting guerryer at coordinates -200 78 192 off the roof when he got dragged back for speed randomly!

**Comment by joehot200** [comment]
Note to self: Do a cone velocity area of larger radius as opposed to a spherical velocity area with a smaller radius to solve these kinds of drag backs.

**Comment by joehot200** [comment]
Extra velocity leniency has been added for the next update on the X/Z plane. 

A velocity cone of knockback should be added but that can come later.
