### ISSUE TITLE
No dragbacks speed bypass! (config changes?)

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#48]
**Screenshot (or video recording):** https://gyazo.com/1358d436ffa4060e1b57feb4a970add4

**AntiAura version:** 10.99

**Hacked Client (Set to N/A is none):** Flux B11

**Description:** ... how is this not blocked? Is this a problem with the default config?

**Comment by joehot200** [comment]
It looks like I made the default configuration too lenient, I will tighten up the leniency for the next update slightly.

**Comment by EthanTG** [comment]
@joehot200 I would also like to mention that NoSlowdown does not block webs...
