### ISSUE TITLE
Add a new step value

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#49]
**Name of feature:** Add CheckOnlyIfSmooth: true

**Description:** This will make Step check only if the player using step is using smooth step... most people use smooth step and this will prevent 1.10+ blocked auto jump from being blocked since it's not "smooth." This is for single block step!

It's just... IDK any clients that are 1.10+ that offer smooth Step so...

And also, smooth Step is usually slower than normal Step. That's how can tell it apart. And... idk if i have to say this... but smooth Step is SMOOTH!

**Comment by joehot200** [comment]
This would offer negligible advantage against a minority of clients, and so therefore I won't be implementing it.
