### ISSUE TITLE
FastBreak FP (ADD VERBOSE!)

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#50]
**Screenshot (or video recording):** None AT THE MOMENT

**AntiAura version:** 10.99

**Hacked Client (Set to N/A is none):** Flux B11

**Description:** Sometimes, when breaking blocks that I have built, they still stay there. I think this may be a false positive with FastBreak, but I am unsure because there is no verbose so please add a verbose OPTION. It will be off by default though.

**Comment by joehot200** [comment]
Needs more information, as this hasn't been duplicatable.
