### ISSUE TITLE
NoSlowdown not blocked for webs + Jesus WITH speed bypass! 

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#54]
**Screenshot (or video recording):** https://youtu.be/l-Kcu9Q4fTo

**AntiAura version:** 10.99

**Hacked Client (Set to N/A is none):** Flux B11

**Description:** idk if webs are blocks for noslow but I think they are

**Comment by joehot200** [comment]
Fixed for 11.01
