### ISSUE TITLE
Recode config!

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#55]
So I was respacing things in the config (which would cause problems) and changing the names of values and check names to make them less confusing and more easy to understand, but that means you have to recode the config @joehot200... are you willing to do this? This does not have to come out in 11.0, but it could... otherwise it could come out in 11.1-11.10?

**Comment by ItsMennyo** [comment]
:///

**Comment by EthanTG** [comment]
Closed - Fixed in 11.0 already (new recode may be coming)
