### ISSUE TITLE
Fall Damage Issue

### ISSUE THREAD

**Issue by ePocalypse** [EthanTG/AntiAura#57]
Issue with the plugin.
If you shift out on a block for a few seconds you get teleported to the ground and so you avoid the fall damage

**Comment by EthanTG** [comment]
Duplicate of issue #43. No evidence has been provided here either.

**Comment by joehot200** [comment]
Hi there @ePocalypse, 

I have briefly tested this by simply building a tower, walking to the edge, and shifting.

However I wasn't able to duplicate this issue.

Could you please give me more information about the problem?

![image](https://user-images.githubusercontent.com/6872507/28795691-b7976bae-7632-11e7-974a-173146df8dca.png)

**Comment by joehot200** [comment]
Fixed for 11.01

**Comment by EthanTG** [comment]
Are you going to release a hotfix for 11.0 first @joehot200?

**Comment by joehot200** [comment]
@EthanTG No.

**Comment by EthanTG** [comment]
@joehot200 11.01 will have the fixes?
