### ISSUE TITLE
Reset violations upon unban

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#58]
NOTICE: @joehot200 you must check issue #3 and add /aban for this to work!

**Name of feature:** look at title

**Description:** Upon the automatic unban by /aban, reset all violations. Once i got unbanned after my 10 minutes i accidentally got a false positive and got banned again right away. Clearing away violations after the automatic unban by /aban is the perfect solution to this?

Or...

you could just make a value :) 

ClearViolationsWhenUnbanned: true

**Comment by joehot200** [comment]
It isn't possible to detect when a player is unbanned, and creating a ban system is out of the scope of an anti-hacking plugin.

**Comment by EthanTG** [comment]
@joehot200 i know this is kind of weird, but other anticheats like Spartan have actual commands that are useful. Why can't AntiAura have some of those too, but unique! Also, wouldn't an anti-spambot filter be out of the scope of an anti-hacking plugin? Please respond...
