### ISSUE TITLE
Add extra checks to check for specific hacks.

### ISSUE THREAD

**Issue by joehot200** [EthanTG/AntiAura#59]
Where possible, sub-checks should be created to give more accurate information about the hack used. For example:

- Detect for ScaffoldWalk if the player is trying to scaffold (instead of FastPlace).
- Detect for Flight if the player is detected for Spider but there are no walls near them.
- Detect for NoSlowdown if the player tries to move too fast while eating, blocking, etc.
- Detect for Jesus if the player is moving too fast in/on WATER or LAVA. (added by @EthanTG. Yes it's possible.)

**Comment by ItsMennyo** [comment]
_**Maybe**_ You can recode the checks that you want to split into other checks?

**Comment by joehot200** [comment]
@ItsMennyo there aren't any checks being split into other checks.

**Comment by joehot200** [comment]
Done.
