### ISSUE TITLE
Block AutoArmor, InvMove, AutoPot, Strafe

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#6]
Block AutoArmor, InvMove [impossible actions], AutoPot [throwing pots from inventory while pvp'ing], Strafe [speed]

**Comment by joehot200** [comment]
As AutoArmour (during movement and PVP) and InvMove have been blocked, I am closing this.

Please create a separate issue for AutoPot (though it may not be blockable) and Strafe.

**Comment by EthanTG** [comment]
@joehot200 Reopening. AutoArmor must be blocked during normal movements too such as just standing still and it's kicked for AutoSoup which may confuse some.

**Comment by EthanTG** [comment]
Fine fine if you want to do it this way....

This issue will be reviewed in the future though.
