### ISSUE TITLE
Random flight dragback when jumping onto a block

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#60]
**Screenshot (or video recording):** https://youtu.be/_T-Sm-yVDK0

**AntiAura version:** 10.99

**Hacked Client (Set to N/A is none):** Flux B11

**Description:** I jumped up a grass block and immediately got kicked for flight! This is the default config!!!! I seriously only removed autobanning...

**Comment by joehot200** [comment]
Fixed.
