### ISSUE TITLE
XRay not working properly?!

### ISSUE THREAD

**Issue by ItsMennyo** [EthanTG/AntiAura#61]
Info:
- Type: Bug
- Client: Wurst MC 1.12
- Server: ItsMennyo Network 2.0
- AntiAura version: 10.99
- Config: Custom (XRay settings: https://hastebin.com/deqanovepu.bash)
- Check: XRay

Description:
- XRay does not seem to work well. It seems that the interval is every 20 ticks but as you can see on the config I have the lower than that.
- And it does not seem to update all the way the player is running at this time but more the path I've been running.

Video/Proof:
https://gyazo.com/b569942a519d388d36d2474fcb35380f
https://ibb.co/cA689k

**Comment by ItsMennyo** [comment]
**Also** add blockage for mossy_cobblestone (ID: 48) and mob_spawner (ID; 52): https://gyazo.com/46d2a6b0273a067efa9c17a4d30cd6aa

**Comment by joehot200** [comment]
Blocking mossy cobble, as well as spawners, would require me to make an extra distance revealing task, which would be significantly laggy simply to block one minor thing. At the moment, I've made the decision to not implement this. Unnecessary lag is never a good thing.

Make sure you have a proper X-Ray configuration.

Such as:
  XRay:
    #Enable the blockage of X-Ray?
    Enabled: true
    #The X-Ray task is done every (HowOften * IntervalMult). IntervalMult cannot be less than 1.
    #Increasing improves performance.
    IntervalMult: 1
    #This will not hide blocks if they have a non-solid blocks around them.
    #For example if a diamond block has got 1 air block above it, it will not be hidden.
    #But if it is encased in stone, it will be hidden.
    #Enabling this costs a small amount of performance, as it must check all blocks around the block being hidden.
    ShowBlocksIfExposedToAir: false
    #The maximum chunks every time the X-Ray checker runs it's X-Ray blocking task (at each IntervalMult).
    #This is to stop players flying really quickly around the world from making 50 chunks be loaded at a time, causing huge lag spikes.
    #However lower values may make chunk ores hide slower than normal.
    #Higher values are more prone to lag spikes but make XRay blockage better.
    #Lower values mean that the area around a player takes time to have ores hidden, but improves performance.
    MaxChunksPerIntervalMult: 2
    #How far away in chunks should the X-Ray check look for blocks to hide?
    #Decreasing this significantly performance, but decreases range in which blocks are hidden.
    ChunkDistance: 5

**Comment by ItsMennyo** [comment]
Oh now it works better but more server lagg :/

And can you not make it that the mossy cobble and spawners will be hidden in the same way as the ores?

**Comment by EthanTG** [comment]
I have experienced this bug before..
