### ISSUE TITLE
Cocoa FastBreak :/

### ISSUE THREAD

**Issue by ItsMennyo** [EthanTG/AntiAura#62]
I do not have time to explain this issue so look at this:
https://gyazo.com/9d008efcea1cd99eb32cc2080f535b96

**Comment by EthanTG** [comment]
ok...

fastbreak detected when breaking a cocoa bean 😂 

are you sure he/she wasn't using fastbreak :/

**Comment by ItsMennyo** [comment]
She is a Mob lol

**Comment by joehot200** [comment]
Could not duplicate on 11.0 test version.
