### ISSUE TITLE
[PRE-11.0] CRITICAL GLIDE BUG

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#63]
**Screenshot (or video recording):** https://youtu.be/VUftZSXsj3w

**AntiAura version:** Pre 11.0 (OTS)

**Hacked Client (Set to N/A is none):** Flux B11

**Description:** I joined the game and immediately after joining I start getting teleported up and down and up and down until I got kicked for Glide!!

**Comment by joehot200** [comment]
Fixed.
