### ISSUE TITLE
New notification: "attempted"

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#66]
**Name of feature:** New "attempted" notification for /anotify.

**Description:**

Example:

EthanTGYT attempted: FastBreak
EthanTGYT attempted: AntiKB

To notify operators on specific hacks that weren't blocked for debugging.

**Comment by joehot200** [comment]
This would spam people with false information. :/

**Comment by EthanTG** [comment]
Until you fixed the bugs...

This would allow people to report more bugs on those checks and that means you can fix them asap. Additionally, you could still keep this here :)


And people get spammed any way! (Ahem issue #27)

**Comment by joehot200** [comment]
Won't be doing this.
