### ISSUE TITLE
Criticals false positive bug 10.97

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#7]
**Screenshot/Video:** N/A

**AntiAura version:** 10.97

**Description:**
Tested on the official test server. Player had effect regeneration on for 600 seconds with amplifier 20 and surrounded by 150 zombie pigman in lava and he was fighting them all in the lava when he got kicked 3 times for criticals when he was playing legit.

**Comment by joehot200** [comment]
@EthanTG I need more information about this. Are you saying that this is SPECIFICALLY a bug ONLY to do with players being in water/lava and fighting?

Please clarify the specific situations in which this issue occurs.

**Comment by EthanTG** [comment]
@joehot200 Unknown. All I know is that this only happened in the lava.

**Comment by joehot200** [comment]
Problems with lava and water have been solved, so I'm marking this one as solved. 

I also made the criticals threshold decrease over time a bit more than previously.
