### ISSUE TITLE
NoFall not working Vs. Wolfram9.4 MC1.12

### ISSUE THREAD

**Issue by 10axl** [EthanTG/AntiAura#71]
**Screenshot (or video recording):** 
If you need better quality let me know (used an nVidia preset)
https://www.youtube.com/watch?v=IUkSTPcIaGo

**AntiAura version:**
11.0

**Hacked Client (Set to N/A is none):**
Wolfram 9.4 for MC1.12

**Description:**
As seen in the video, the NOFALL by wolfram caused me to not take damage. This could provide a very unfair advantage. 

If you need anything else, please let me know.

Thank you,
10axl

**Comment by joehot200** [comment]
Thanks for the report @10axl, I'll get around to investigating this ASAP.

**Comment by EthanTG** [comment]
Could you type /about AntiAura and send a screenshot of the message please @10axl?

**Comment by 10axl** [comment]
I see EthanTG, you think i'm stupid :P JK. Here you go.

Screenshot:
http://imgur.com/a/AS5Ai

Sorry for the delay, was up most of the night programming.

Let me know if there is anything else I can do.

Thank you,
10axl

**Comment by EthanTG** [comment]
Sorry @10axl, I just wanted to make sure you weren't a Spartan fanboy trying to "lie" :/ i'm very suspicious. I don't think you're stupid. Nothing else you need to do. Thanks!

**Comment by EthanTG** [comment]
@10axl Resolved. Please download 11.01.
