### ISSUE TITLE
My Problem is Speed.

### ISSUE THREAD

**Issue by YONONH** [EthanTG/AntiAura#76]
New Version Flight it's good. but Speed it's have too problem. it's spam my server and kick lag people it's said sprint hack. Please Fix :+1:

**Comment by EthanTG** [comment]
@YONONH Please use the correct format next time when submitting an issue. Could you link a video to this issue? I believe it is quite rare.

**Comment by YONONH** [comment]
when someone is lag and he's drag back. when he move he will be kick by server. and i want to config to disable sprint because it's make lag people have problem.
