### ISSUE TITLE
Flight and JoinTeleport issue! (Extreme) 11.01 (AntiAura)

### ISSUE THREAD

**Issue by Simon942** [EthanTG/AntiAura#77]
*Delete the lines with single or triple asteriks (italicized). They are comments for YOU!*

*If you are SUGGESTING new features.,* ***DELETE THIS SECTION!***

*The title of your report should be related to the body*

REQUIRED FORMAT:

**Screenshot (or video recording):** 
https://www.youtube.com/watch?v=_cFdBudZYjk&feature=youtu.be

**AntiAura version: 11.01

**Minecraft version: 1.11.2 Optifine HD Ultra C3. Server (1.8.8) Spigot

**Hacked Client (Set to N/A if none): N/A

**Description: SO extreme dragbacks, U can't jump!!!

*Should you be unable to provide information for a certain requirement, your bug may be closed unless you add further information or get low priority.*

*If you are NOT suggesting new features,* ***DELETE EVERYTHING BELOW THIS!***

***How to suggest new features:***

*Title of suggestion should be related to the body*

**Name of feature: Flight and JoinTeleport

**Description: Dragbacks EXTREME

**Comment by EthanTG** [comment]
@Simon942 Please read the instructions in the issue template next time and remove comments with single or triple asterisks. @joehot200 you figure this out i don't do 1.12
