### ISSUE TITLE
Unknown NoFall kicks in water

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#78]
**Screenshot (or video recording):** https://gyazo.com/2268ff825e8a16035e139597a13e31fc

**AntiAura version:** 11.01 (OTS)

**Minecraft version:** 1.8.8 Flux Build 11 Client

**Hacked Client (Set to N/A if none):** Flux B11 

**Description:** First, I used jesus at the pool at /warp jesus and after halfway across I got dragged back for speed and then I suddenly started getting randomly kicked for NoFall again and again when I wasn't using NoFall.

**Comment by joehot200** [comment]
Fixed in 11.03.
