### ISSUE TITLE
Jesus bypass 

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#79]
**Screenshot (or video recording):** https://gyazo.com/45ea1963876ad910b7c8dabf3ba6e33c

**AntiAura version:** 11.01 (OTS)

**Minecraft version:** 1.8.8 Flux B11 client

**Hacked Client (Set to N/A if none):** Flux B11

**Description:** N/A (A full video can be requested by messaging me on discord @joehot200)

**Comment by joehot200** [comment]
Fixed in 11.07.
