### ISSUE TITLE
X-Ray too performance intensive

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#8]
X-Ray is still too performance intensive. Please fix it in 11.0. 

Note for Joe:
"Make X-Ray change blocks on chunk load and then drastically decrease checked radius."

**Comment by ItsMennyo** [comment]
Fixed in 10.97b1

**Comment by joehot200** [comment]
Fixed in 10.98.

**Comment by EthanTG** [comment]
@joehot200 this is 10.97-b1?

**Comment by ItsMennyo** [comment]
It is kind of fixed so IDK

**Comment by EthanTG** [comment]
lol i have a bypass already
