### ISSUE TITLE
Typo in the Criticals check

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#80]
**Screenshot (or video recording):** 
![2017-08-11_13 06 45](https://user-images.githubusercontent.com/29691919/29223873-18406e0e-7e96-11e7-82e2-e96cdeb158d0.png)

**AntiAura version:** 11.01 + NCP 3.15.1-RC-sMD5NET-b1084 (OTS) 

**Minecraft version:** 1.8.8 Flux B11

**Hacked Client (Set to N/A if none):** Flux B11

**Description:** I failed Critcals and not Criticals.

**Comment by EthanTG** [comment]
Closed as this is a typo with AntiAuraMessages and not AntiAura.

**Comment by joehot200** [comment]
This was an AntiAura bug.

**Comment by joehot200** [comment]
Fixed for 11.02

**Comment by EthanTG** [comment]
@joehot200 no it is not. I have identified the error. I made AntiAura output it by saying %HACKNAME% is not allowed and Criticals is typed correctly?
