### ISSUE TITLE
AutoSoup - Not triggering (Multiple Delays)

### ISSUE THREAD

**Issue by CallmeSimon** [EthanTG/AntiAura#81]
**Screenshot (or video recording):** 
https://youtu.be/KK5keZze708?t=4m21s

Check from the specified time in the URL (4 minutes and 21 seconds, the first 4 minutes is just me on your discord // ShadowPlay<)

**AntiAura version:**
11.01

**Minecraft version:**
1.7 // Protocol Support (1.7, 1.8, 1.9+)

**Hacked Client (Set to N/A if none):**
Jigsaw

**Description:**
We're primarily using Anti-Aura for our KitPvP server, which means we're depending on AutoSoup as a vital feature of whichever Anti-Cheat we do decide to go with. We tested it using Jigsaw client which in many cases seems to be the "go-to" client for many of the players who get banned on our Network. Therefor, it'd obviously be preferred if everybody using the AutoSoup in the specified client did get banned automatically.

- Before you search up my username on Spigot and find out I ain't the person who purchased your plugin, it was purchased for our Network, the purchase is under the username JKnetz.

Granted we need to prove purchase, that'll obviously be possible.

**Comment by EthanTG** [comment]
@CallmeSimon Can I have the IP to your server? I'm labeling this is critical until I can confirm whether or not this only happens on your server. Can you show me the Soup check in the AntiAura config?

**Comment by CallmeSimon** [comment]
@EthanTG We're currently using it on our test server for our kitpvp server, the ip is pvp.sc nevertheless.

Hand me your username so we can whitelist you on /server testkit

As for our Soup check:
http://jknetz.com/u/gzr18xqcpa4pte5.png

As seen in that, our latest test was with 250.

**Comment by joehot200** [comment]
@CallmeSimon Despite not having changed the AutoSoup code for over a year, I've checked it and code-wise it still looks just as solid as it always has been. I'll download Jigsaw and test this though.

**Comment by joehot200** [comment]
Also.. WHY is EthanTG claiming AntiAura doesn't block AutoSoup when there's literally a configuration section (albeit 5 lines) all about AntiAura's blockage of AutoSoup?

**Comment by EthanTG** [comment]
@joehot200 I corrected my mistake quickly ._. 

I've already tested this. The "bypass" exists.
