### ISSUE TITLE
Freecam not blocked! 

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#84]
**Screenshot (or video recording):** 
![2017-08-12_20 48 02](https://user-images.githubusercontent.com/29691919/29245173-c8527ae4-7f9f-11e7-9d78-b1debccea468.png)
![2017-08-12_20 48 11](https://user-images.githubusercontent.com/29691919/29245174-c854ae54-7f9f-11e7-87b2-1a05e4f9b163.png)

**AntiAura version:** 11.02

**Minecraft version:** 1.8.8

**Hacked Client (Set to N/A if none):** Flux B11

**Description:** On creepax.net:26495. Freecam bypasses through walls.

**Comment by joehot200** [comment]
Not a bypass, and cannot be blocked.

**Comment by EthanTG** [comment]
@joehot200 thought Freecam was blocked for entities?
