### ISSUE TITLE
Regen bypass

### ISSUE THREAD

**Issue by Simon942** [EthanTG/AntiAura#85]
https://youtu.be/mm8Sk9_QDDM

AntiAura 11.02

Minecraft version 1.8.8 

Hacked client: LiquidBounce 1.8.8

Regen can be bypassed on 40% speed! You regen like sonic, if you just have food in your foodbar.

HIGH priority

**Comment by joehot200** [comment]
Hi @Simon942, 

I've decreased MaxHeartsPerSecond to 4.0 for the default in next update.

The default was 5.0. However that was too lenient.

If you change MaxHeartsPerSecond to 4.0 in the config, this problem should be solved.

Thanks for letting me know.
