### ISSUE TITLE
NoWeb Bug

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#88]
**Screenshot (or video recording):** https://youtu.be/tJytbSPLc8U

**AntiAura version:** 11.02

**Minecraft version:** 1.8.8

**Hacked Client (Set to N/A if none):** Flux B11

**Description:** IP: creepax.net:26495. I was using speed through webs for less than a second and suddenly I kept getting dragged back for speed even when I turned it off!

**Comment by joehot200** [comment]
Fixed for 11.03
