### ISSUE TITLE
NoFall random void kick 

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#95]
**Screenshot (or video recording):** https://youtu.be/WDnZDzHL1oU

**AntiAura version:** 11.02

**Minecraft version:** 1.8.8

**Hacked Client (Set to N/A if none):** NONE

**Description:** Falling in the void on siecraft.dk kicks me for NoFall

**Comment by joehot200** [comment]
I think I fixed thkz

**Comment by joehot200** [comment]
This*
