### ISSUE TITLE
Jumping on ender chest Spider dragback

### ISSUE THREAD

**Issue by EthanTG** [EthanTG/AntiAura#97]
**Screenshot (or video recording):** https://gyazo.com/89d10b1e70b8dd74cf40e8ca3c4b02cb

**AntiAura version:** 11.03

**Minecraft version:** 1.8.8

**Hacked Client (Set to N/A if none):** None (just my space bar xd)
 
**Description:** I was jumping up an ender chest on an oak plank and I got dragged back...

IP: luzonmines.net Config is unmodified I think besides punishments

**Comment by joehot200** [comment]
Could not duplicate on 11.06.

**Comment by EthanTG** [comment]
@joehot200 don't close issues that you can't duplicate yet. It's obviously there. Leave it open for future reference (aka come back to this..)

**Comment by A248** [comment]
I have experienced this same issue with enderchests and anvils.

I think that AntiAura detects the player as being beside the enderchest block, rather than simply on the edge of the oak plank block.

**Comment by EthanTG** [comment]
Yes it's possible.

**Comment by joehot200** [comment]
Fixed for 11.08.
